### PR TITLE
code restructured

### LINKED ISSUE #24: Code restructuring
# I'm submitting a 
- [x] Code improvement

## Current Behaviour:
Currently the flask backend only contains a single file `app.py` which contains all its code. 

## Expected Behaviour:
Create a separate directory for the backend and to seperate helper functions from the main server file. 

## Do you want to work on this issue?
Yes

### PR DESCRIPTION
**Pull request by khareyash05**
Fixes #24 

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description
Code restructuring done

### CODE REVIEW

**Comment by khareyash05** [comment]
@Mec-iS Have a look!

**Comment by Mec-iS** [comment]
could you double-check why the build in Travis is failing and try to fix it?

**Comment by khareyash05** [comment]
@Mec-iS I think since node-sass is deprecated and thus error because the error in build starts up at node-sass

**Comment by khareyash05** [comment]
@Mec-iS I am not able to find a soution.Kindly help

**Pull request merged**
