### PR TITLE
changed bg of hydra graph

### LINKED ISSUE #51: UI/Responsiveness
The GUI has a lot of great additions and new UX features that we would like to merge into the master branch. However, we need to solve this two small but important layout problems we added:

- For some reason the background of the graph is now white and not using the light gray that we have for the graph area
- The height is not really responsive and in a lot of screens due to some modifications right now we just have a white area below

Before:
image

Now:
image

### PR DESCRIPTION
**Pull request by khareyash05**
Fixes #51

### CODE REVIEW

**Comment by Mec-iS** [comment]
hi @khareyash05 
thanks for the PR. Could you first give a look to #72 and give a review there so we can merge that one before merging this one?

**Comment by khareyash05** [comment]
Ya sure @Mec-iS

**Comment by khareyash05** [comment]
Hey @Mec-iS  is there any server for the organization to dicuss like Discord/Slack

**Comment by Mec-iS** [comment]
sure, please join https://join.slack.com/t/hydraecosystem/shared_invite/zt-ly4j3hg3-gVhJxgc6ykpGrel_N4Xvvg

**Comment by khareyash05** [comment]
Thanx @Mec-iS is my PR ready to merge??

**Comment by Mec-iS** [comment]
Please rebase from `develop`

**Comment by Mec-iS** [comment]
Also, checks on Travis should be successful

**Comment by khareyash05** [comment]
@Mec-iS could you pls tell me what git commands to follow to rebase from develop

**Comment by Mec-iS** [comment]
try first `git pull origin develop` (in your local develop branch), then `git merge develop` (from your branch).

See [this page](https://www.atlassian.com/git/tutorials/merging-vs-rebasing).

**Comment by khareyash05** [comment]
@Mec-iS rebased branch from develop but checks are failing

**Comment by Mec-iS** [comment]
Please [check why it is failing](https://app.travis-ci.com/github/HTTP-APIs/hydra-python-agent-gui/builds/243190464) and try to find a fix.

**Comment by khareyash05** [comment]
@Mec-iS I am not able to find a fix Kindly help.

**Comment by khareyash05** [comment]
@Mec-iS Could you pls have a look at this as well

**Pull request merged**
