### PR TITLE
Added updates as per issue #10 fixes all of them 

### LINKED ISSUE #10: UX Enhancements
There are some things which could make the experience a little bit cleaner:

- Default operation now is the first one listed in the Hydra Doc. Making the GET as default would be better to fast querying around Endpoints.

- Saving Operations State. Properties have their own state so you can go around and come back and the values will be there. States are lost when you switch endpoints.

- Button to clean properties. If you need to clean the form now you have to erase property by property.

These could be tackled one by one.

### PR DESCRIPTION
**Pull request by sudipt1999**
As described by @Guttz  in #10, setting the GET as default would be a better option and would make a general way since it will be default for all endpoints. So, this pr fixes that, a proof of screenshot is attached below kindly let me know if I changes required.

### CODE REVIEW

**Comment by sudipt1999** [comment]
Updates added to the pull requests are
1. Added a Clear form button to clear the form fields values since we have to manually delete them all curently.
2. Added localstorage to the app for storing the properties and resourceIDs fields value, I have tested out them properly but will request a final check from the mentors.

Screenshot from 2020-03-10 14-46-39

**Comment by Guttz** [comment]
Hey @sudipt1999, thanks for the contributions! The localstorage caching is also a good idea. I'll add some modifications we have to work on to merge the PR.

**Comment by sudipt1999** [comment]
@Guttz  Thanks for revewing the changes, as asked I will fix the error above also I wil move the clear button to form top. Sorry for opening the PRs at ```master``` branch, I will keep this in mind for the future pr.
Thank you

**Comment by sudipt1999** [comment]
Updates done 
1. Fixed the localstorage error 
2. Placed the clear button at right corner of form also checked for responsiveness!
Screenshot from 2020-03-10 21-54-23

**Comment by sudipt1999** [comment]
@Guttz I have added changes as requested, kindly review the changes.

**Pull request merged**
