### PR TITLE
github source

### PR DESCRIPTION
**Pull request by thrishik7**
issue:#11

changes made:
added github icon, near hydrus icon to direct source code.
Screenshot from 2020-03-09 19-32-29

### CODE REVIEW

**Comment by thrishik7** [comment]
@xadahiya @chrizandr review my pull request.

**Comment by Guttz** [comment]
Hey @thrishik7, thanks for the PR. New PRs should be on the develop branch. Could you please open it on the develop branch instead of the master  branch?

**Comment by Mec-iS** [comment]
I changed the target base to `develop`

**Comment by thrishik7** [comment]
@

> Hey @thrishik7, thanks for the PR. New PRs should be on the develop branch. Could you please open it on the develop branch instead of the master branch?

@Guttz  fine, I will work on it

**Comment by xadahiya** [comment]
Please resolve the conflicts

**Pull request closed without merging**
