### PR TITLE
moved to es6, changed all var to let

### PR DESCRIPTION
**Pull request by sudipt1999**

### CODE REVIEW

**Comment by Guttz** [comment]
Can you fix the conflicts? The ones under build are not that important but the ones under src have to be resolved manually. If you are not able to do it I can help out later. Thanks.

**Comment by sudipt1999** [comment]
Sire @Guttz , i will fix them incase help required I will surely ask.

**Comment by sudipt1999** [comment]
@Guttz I fixed the conflicts, they were because of the pr merged for issue #5, also I build the changes and solved the build conflicts! kindly recheck it from your side.

**Comment by sudipt1999** [comment]
@Guttz should I change all the functions to arrow functions, kindly let me know!

**Comment by Guttz** [comment]
Yeah, sure. The code would be probably a bit more concise. I'll open an issue with a list of code quality related points we can work on.

**Comment by Guttz** [comment]
https://github.com/HTTP-APIs/hydra-python-agent-gui/issues/45

**Pull request merged**
