### PR TITLE
hover effect and click event listener

### PR DESCRIPTION
**Pull request by thrishik7**
issue: #5 

added hover effect on nodes and onclick listener on the nodes, clicking on the endpoint nodes will initiate that endpoint's operation in the console.
ezgif com-crop

### CODE REVIEW

**Comment by xadahiya** [comment]
Please post before/after screenshots and remove redundant log statements from your code.

**Comment by thrishik7** [comment]
@xadahiya okay, I will add those with the click event listener.

**Comment by thrishik7** [comment]
added hover effect on nodes and onclick listener on the nodes, clicking on the endpoint nodes will initiate that endpoint's operation in the console.
ezgif com-crop

@xadahiya , please review my pr. I will continue adding other functionalities.

**Comment by xadahiya** [comment]
@Guttz

**Comment by Guttz** [comment]
That's looks nice. I'll do some testing on this one. 

By the way, are you using ESLint? I would suggest doing so, there is some room for improvement in the code, including in what I wrote in the past :)

**Comment by thrishik7** [comment]
> @thrishik7 I am not sure but redux is being added as dependency in the project, currently we are not using any state management library, @Guttz @xadahiya kindly look through this !

@sudipt1999 I thought of using redux to change the state of siblings component from hydragraph component, but later implemented using function. Will remove those dependency :)

**Comment by thrishik7** [comment]
> That's looks nice. I'll do some testing on this one.
> 
> By the way, are you using ESLint? I would suggest doing so, there is some room for improvement in the code, including in what I wrote in the past :)

yes @Guttz  , okay will continue improving those conflicts, and remove other unused code

**Comment by sudipt1999** [comment]
@thrishik7 other than that I am looking forward to seeing it merge ! good work though!

**Comment by thrishik7** [comment]
@Guttz @xadahiya , removed conflicts and other unused code. Please review my pr

**Comment by Guttz** [comment]
I'm going already merge this, but we need two modifications that I'll mention here and in issue https://github.com/HTTP-APIs/hydra-python-agent-gui/issues/5.

- I would suggest that the hover color modification should only happen on clickable nodes, not on every node.
- Another great addition would be click support for requests: If a click on a PUT Node that has a CommandCollection parent node, I could both set the collection and also the request type.

**Comment by thrishik7** [comment]
@Guttz , yeah I started working on it , okay I will start adding those as well.

> I'm going already merge this, but we need two modifications that I'll mention here and in issue #5.
> 
> * I would suggest that the hover color modification should only happen on clickable nodes, not on every node.
> * Another great addition would be click support for requests: If a click on a PUT Node that has a CommandCollection parent node, I could both set the collection and also the request type.

**Comment by Guttz** [comment]
Great, thanks. Open a new PR when you implement them and mention issue 5 again.

**Pull request merged**
